on:
  schedule:
    - cron: 0 0 * * * # every day at 00:00
  repository_dispatch: # run manually
    types: [check-link]

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2