name: Broken link check
on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight (UTC)
  workflow_dispatch:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://docs.platform.planqk.de/"
          # optional:
          #honorRobotExclusions: false
          #ignorePatterns: "github,google"
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"